baseURL = "https://bsidestlv.com/"
languageCode = "en"
title = "BSidesTLV 2020"

# Theme
theme = "devfest-theme-hugo-2020"

# Params

enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true
disablePathToLower = true
googleAnalytics = "UA-171723556-1"
enableGitInfo = true

[params]
    title = "BSidesTLV 2021"
    date = "2021-07-22"
    description = "BSides creates opportunities for individuals to both present and participate in an intimate atmosphere that encourages collaboration. It is an intense event with discussions, demos, and interaction from participants. It is where conversations for the next-big-thing are happening."
    images = ["/images/social-share.jpg"]
    email = "info@bsidestlv.com"
    keywords = "event, bsidestlv, bsides, telaviv, tel-aviv, security, cybersecurity"
    tags = "event, bsidestlv, bsides, telaviv, tel-aviv, security, cybersecurity"
    copyright = "We :heart:Ô∏è TLV"
    cfpUrl = "https://cfp.bsidestlv.com/bsidestlv-2021/cfp"
    subscriptionUrl = "https://e.bsidestlv.com/subscription/lGCnPUft?locale=en-US"
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#000"
    googleWebmasterKey = ""
    googleMapsApiKey = "AIzaSyAWrX0-FFQ3oJhCjxRgEBbD8FObWg1FXI0"

[params.logos]
    jumbo = "/images/logos/bstlv_color.png"
    header = "/images/logos/bstlv_color.png"
    footer = "/images/logos/bstlv_color.png"

[taxonomies]
  tag = "tags"

[markup.goldmark.renderer]
unsafe= true

[[menu.main]]
    identifier = "cfp"
    name = "CFP"
    url = "https://cfp.bsidestlv.com/bsidestlv-2021/cfp"
    weight = 190
    external = true