[build]
publish = "public"
command = "yarn run build"

[build.environment]
HUGO_VERSION = "0.81.0"
HUGO_ENABLEGITINFO = "true"
# GOOGLE_MAPS_API_KEY should be set in Netlify's environment variables UI, not here

[context.production.environment]
HUGO_ENV = "production"
NODE_ENV = "development"
